services:
  octo:
    build:
      context: octo
      dockerfile: Dockerfile
    container_name: octo
    command: ["bash", "-c", "/home/sites/octo/run_finetune.sh"]
    tty: true
    env_file:
      - ./octo/server.env
    volumes:
      - ./octo:{MOUNT_PATH}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
