services:
  octo:
    build:
      context: octo
      dockerfile: Dockerfile
    container_name: octo
    entrypoint: ["bash", "mnt/docker_entrypoint.sh"]
    tty: true
    # stdin_open: true
    env_file:
      - ./octo/local.env
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: all
            capabilities: [ gpu ]
    volumes:
      - ./octo:/home/sites/octo/mnt
